### ISSUE TITLE
Throws errors on Kube 1.8+

### ISSUE THREAD

**Issue by sdague** [IBM/metrics-collector-client-kubernetes#5]
> kubectl logs lovely-sasquatch-ny-power-metrics-rhlg2
Error from server (Forbidden): nodes is forbidden: User "system:serviceaccount:default:default" cannot list nodes at the cluster scope
Error from server (Forbidden): pods is forbidden: User "system:serviceaccount:default:default" cannot list pods in the namespace "kube-system"
Error from server (Forbidden): configmaps "cluster-info" is forbidden: User "system:serviceaccount:default:default" cannot get configmaps in the namespace "kube-system"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   315    0    11  100   304     57   1589 --:--:-- --:--:-- --:--:--  1591
{"ok":true}

The collector assumes a certain level of access. It would be best if this created a dedicate role that allowed those permissions just for the job in question.

**Comment by Tomcli** [comment]
A quick way to fix this is to apply a view role to the job.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tracker
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name:  tracker
    namespace: kube-system
```
This means the job is able to read all the secrets and configmap in kube-system. I am fading out of this project, so I am not sure does it involve any legal stuff.
